name: hw
description: Home work application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

#flutter pub upgrade --major-versions
#flutter pub run build_runner build --delete-conflicting_outputs
#flutter pub run flutter_launcher_icons:main
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  path_provider: ^2.0.10

  json_annotation: ^4.5.0

  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  json_serializable: ^6.2.0
  http: ^0.13.4
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1

  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  flex_color_scheme: ^5.0.1

  drift: ^1.6.0
  sqlite3_flutter_libs: ^0.5.7
  shared_preferences: ^2.0.15

  firebase_core: ^1.17.1
  firebase_crashlytics: ^2.8.1


  flutter_launcher_icons: ^0.9.2

flutter_icons:
  ios: true
  image_path: "assets/launch_icon.png"
  remove_alpha_ios: true

  android: true
  adaptive_icon_foreground: "assets/launch_icon.png"
  adaptive_icon_background: "#FFFFFF"


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.1.11
  json_serializable: 6.2.0
  drift_dev: 1.6.0


  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/backgrounds/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
      - family: KingthingPetrock
        fonts:
          - asset: assets/fonts/kingthing_petrock.ttf

      - family: Pacifico
        fonts:
          - asset: assets/fonts/pacifico.ttf

      - family: MarriageAnt
        fonts:
          - asset: assets/fonts/mariage_ant_d.ttf

      - family: BadScript
        fonts:
          - asset: assets/fonts/bad_script.ttf
